### ISSUE TITLE
Function Default Arguments breake reflection

### ISSUE THREAD

**Issue by OrangeFlag** [JetBrains/kotless#1]
Example:
```
@Get("/")
fun root(country: String? = null): String {
    return "4"
```

Log:
```
WARN Reflections:396 - could not get type for name org.orangeflag.RootKt.root from any class loader

org.reflections.ReflectionsException: could not get type for name org.orangeflag.RootKt.root
at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
at org.reflections.util.Utils.getMemberFromDescriptor(Utils.java:80)
at org.reflections.util.Utils.getMethodsFromDescriptors(Utils.java:101)
at org.reflections.Reflections.getMethodsAnnotatedWith(Reflections.java:482)
at io.kotless.dsl.reflection.ReflectionScanner.funcsWithAnnotation(ReflectionScanner.kt:26)
at io.kotless.dsl.dispatcher.RoutesCache.scan(RoutesCache.kt:71)
at io.kotless.dsl.Application.init(Application.kt:20)
at io.kotless.dsl.LambdaHandler.handleRequest(LambdaHandler.kt:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:350)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:293)
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114)
Caused by: java.lang.ClassNotFoundException: org.orangeflag.RootKt.root
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
... 18 more

ERROR LambdaHandler:63 - Error occurred during handle of request and was not caught

org.reflections.ReflectionsException: Can't resolve member named default for class org.orangeflag.RootKt.root
at org.reflections.util.Utils.getMemberFromDescriptor(Utils.java:94)
at org.reflections.util.Utils.getMethodsFromDescriptors(Utils.java:101)
at org.reflections.Reflections.getMethodsAnnotatedWith(Reflections.java:482)
at io.kotless.dsl.reflection.ReflectionScanner.funcsWithAnnotation(ReflectionScanner.kt:26)
at io.kotless.dsl.dispatcher.RoutesCache.scan(RoutesCache.kt:71)
at io.kotless.dsl.Application.init(Application.kt:20)
at io.kotless.dsl.LambdaHandler.handleRequest(LambdaHandler.kt:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:350)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:293)
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114)
```

**Comment by TanVD** [comment]
Not reproducible anymore on 1.3.50
