### ISSUE TITLE
Could not initialize class io.kotless.dsl.utils.Json

### ISSUE THREAD

**Issue by BalamChaac** [JetBrains/kotless#36]
Hello I got this error when doing a post and tring to send a json body, when using serialization plugin 
`kotlin("plugin.serialization") version "1.3.72"`

`java.lang.NoSuchMethodError: 'void kotlinx.serialization.internal.SerialClassDescImpl.<init>(java.lang.String, kotlinx.serialization.internal.GeneratedSerializer, int)'
	at club.themba.quiz.Sample$$serializer.<clinit>(Main.kt:17)
	at club.themba.quiz.Sample$Companion.serializer(Main.kt)
	at club.themba.quiz.MainKt.root(Main.kt:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:152)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
	at io.kotless.dsl.reflection.FunctionCaller.call(FunctionCaller.kt:21)
	at io.kotless.dsl.app.http.RoutesDispatcher.processRequest(RoutesDispatcher.kt:46)
	at io.kotless.dsl.app.http.RoutesDispatcher.access$processRequest(RoutesDispatcher.kt:14)
	at io.kotless.dsl.app.http.RoutesDispatcher$preparePipeline$2.invoke(RoutesDispatcher.kt:35)
	at io.kotless.dsl.app.http.RoutesDispatcher$preparePipeline$2.invoke(RoutesDispatcher.kt:14)
	at io.kotless.dsl.app.http.RoutesDispatcher.dispatch(RoutesDispatcher.kt:22)
	at io.kotless.dsl.LambdaHandler.handleRequest(LambdaHandler.kt:54)
	at io.kotless.local.handler.DynamicHandler.handle(DynamicHandler.kt:45)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

reproduce with, 

`@Serializable
data class Sample(var hello:String)

@Post("/hola", MimeType.JSON)
fun root(): String {
    var body = KotlessContext.HTTP.request.myBody?:"""{"hello":"hi"}"""
var bodyJson = parse(Sample.serializer(), body)
    return body.hello
}`

Also with out the plugin I can not use the serialization API from kotlin.

**Comment by shikajiro** [comment]
@BalamChaac 
I had the same error. The problem was that the version of kotlinx-serialization was different from the version on which kotless0.1.3.0 depended.
https://github.com/JetBrains/kotless/blob/master/dsl/common/lang-common/build.gradle.kts#L16

Try setting the version of `org.jetbrains.kotlinx.kotlinx-serialization-runtime` to `0.14.0`.

**Comment by TanVD** [comment]
@shikajiro You are right. Please, use `0.14.0` until I'll update it. I'll add info about it to README.md
