### ISSUE TITLE
Kotless doesn't work with ktor-client

### ISSUE THREAD

**Issue by gumil** [JetBrains/kotless#37]
When adding ktor client into the project:
```
implementation("io.ktor:ktor-client-cio:1.3.2")
```
It shows this error when running:
```
java.lang.NoSuchMethodError: io.ktor.http.content.OutgoingContent$WriteChannelContent.writeTo(Lkotlinx/coroutines/io/ByteWriteChannel;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
	at io.ktor.server.engine.BaseApplicationResponse$respondWriteChannelContent$$inlined$use$lambda$1.invokeSuspend(BaseApplicationResponse.kt:154)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

I only tested locally though. I'm not sure if it affects actual deployment.

**Comment by shikajiro** [comment]
@gumil 
kotless0.1.3 depend on ktor1.2.5.
https://github.com/JetBrains/kotless/blob/master/dsl/ktor/ktor-lang/build.gradle.kts#L10

Let's try it.
```
implementation("io.ktor:ktor-client-cio:1.2.5")
```
Wouldn't it work with

**Comment by TanVD** [comment]
Yep, I'll update Ktor in next release. Probably I have to change version of `ktor` DSL to version of Ktor...
